### ISSUE TITLE
ModuleNotFoundError: No module named 'siringa.api'

### ISSUE THREAD

**Issue by decebal** [h2non/siringa#4]
```
 from .api import *  # noqa
ModuleNotFoundError: No module named 'siringa.api'
```
Running python 3.6 gives me this error, although it installed successfully. Have not tried other versions.

**Comment by tomas-fp** [comment]
I'm running the same version without issues. What version of `setuptools` are you using? Try upgrading it, as well as `pip`, and reinstall `siringa` again.

**Comment by decebal** [comment]
Sorry, my environment is:

```
PYTHON_VERSION 3.6.0
PYTHON_PIP_VERSION 9.0.1
```

**Comment by h2non** [comment]
Try upgrading setuptools, please!
